title = "YM Auto"
slug = "ym-auto"
description = "These sokoban screens were made automatically by computer. Yosio Murase wrote the program that created these levels and then made the levels available on his sokoban web pages."
source = "http://sneezingtiger.com/sokoban/levels/yoshioText.html"
author = "Yoshio Murase"
license = "Copyright Yoshio Murase"
difficulty = "Medium"
year = 1996
version = "0.1" # will make them 1.0 when the whole pack is included

# Walls slightly edited for how the game renders levels

[[levels]]
title = "Level 1"
data = '''
 ######
##  . #
# * # #
# .$  #
#  #$##
## @ #
 #####
'''

[[levels]]
title = "Level 2"
data = '''
#######
#  .@ #
# #.# #
#   $ #
#.$$ ##
#  ###
####
'''

[[levels]]
title = "Level 3"
data = '''
   ####
#### @#
#  *$ #
#     #
## .###
 #$ #
 # .#
 ####
'''

[[levels]]
title = "Level 4"
data = '''
### ###
#.###.#
# #  .#
# $$ @#
#  $  #
#  #  #
#  ####
####
'''

[[levels]]
title = "Level 5"
data = '''
   ####
   # @##
####   #
#. #$$ #
#     ##
#.  $##
##.  #
 #####
'''

[[levels]]
title = "Level 6"
data = '''
#####
# ..####
# $    #
#  #$# #
# @ .$ #
########
'''

[[levels]]
title = "Level 7"
data = '''
  #####
###  .#
# $ # #
# *$  #
# .#@ #
#    ##
#   ##
#####
'''

[[levels]]
title = "Level 8"
data = '''
#######
#.  @.#
#  $# ##
# # $. #
#   $# #
####   #
   #####
'''

[[levels]]
title = "Level 9"
data = '''
#####
#. .###
#.#$$ #
#   @ #
# $#  #
##   ##
 #####
'''

[[levels]]
title = "Level 10"
data = '''
#####
#.  ###
# #   #
# . # #
# $*$ #
##@ ###
 #  #
 ####
'''

[[levels]]
title = "Level 11"
data = '''
########
#.   . #
# # #  #
#@$  $.#
##### $#
    #  #
    ####
'''

[[levels]]
title = "Level 12"
data = '''
####
#  #
#  #####
# .*   #
##$    #
 # #$###
 #. @#
 #####
'''

[[levels]]
title = "Level 13"
data = '''
 #####
 # @ ###
## .   #
#. $.$ #
##$# ###
 #   #
 #####
'''

[[levels]]
title = "Level 14"
data = '''
 #####
##   #
# $# #
# . @##
# *   #
## #$ #
 #.  ##
 #####
'''

[[levels]]
title = "Level 15"
data = '''
 ####
##  ####
#..$  .#
# #$ $ #
#@  #  #
#####  #
    ####
'''

[[levels]]
title = "Level 16"
data = '''
 ######
 #  .@##
 #   $.#
 ###*# #
##     #
#  $  ##
#   ###
#####
'''

[[levels]]
title = "Level 17"
data = '''
 ####
 #@ #
 #  #
##. ####
# $$. .#
#  $ ###
###  #
  ####
'''

[[levels]]
title = "Level 18"
data = '''
#####
#.  #
# # ###
# *$  #
#  $. #
#  @###
#####
'''

[[levels]]
title = "Level 19"
data = '''
  #####
  #   #
  # #.#
###  .#
#@ $$ #
#  .$ #
#######
'''

[[levels]]
title = "Level 20"
data = '''
######
#   @#
# $# ###
# * $  #
#   ## #
##.  . #
 ##   ##
  #####
'''

[[levels]]
title = "Level 21"
data = '''
######
#   @##
#  #  #
#.  $ #
# $$#.#
###  .#
  #####
'''

[[levels]]
title = "Level 22"
data = '''
  ####
###. #
# .  ###
#   $$ #
## . $@#
 #######
'''

[[levels]]
title = "Level 23"
data = '''
 ######
##@.  #
# $$* #
#  #  ##
#  #  .#
#### # #
   #   #
   #####
'''

[[levels]]
title = "Level 24"
data = '''
    ####
    #  #
  ###$.#
  #  . #
###  #.#
# $  $ #
#   #@ #
########
'''

[[levels]]
title = "Level 25"
data = '''
#####
#  .###
# $.. #
#  ##$##
##  #  #
 #$   @#
 #  ####
 ####
'''

[[levels]]
title = "Level 26"
data = '''
  ####
  #  #
  #  ###
### .. #
#  $#  #
#  .$$ #
#### @ #
   #####
'''

[[levels]]
title = "Level 27"
data = '''
#####
#   ###
# # *@##
#  *   #
###$   #
  #   .#
  ######
'''

[[levels]]
title = "Level 28"
data = '''
  ######
### .  #
# $@#. #
#  $# ##
#  *  #
##  # #
 ##   #
  #####
'''

[[levels]]
title = "Level 29"
data = '''
 ####
##  ###
#     ##
#  #$$@#
#  . *.#
########
'''

[[levels]]
title = "Level 30"
data = '''
 #######
##@    #
#. #   #
# $$$.##
# .#  #
#  ####
####
'''

[[levels]]
title = "Level 31"
data = '''
########
#      #
# # ##*#
# #@ $ #
#.$ .  #
#####  #
    #  #
    ####
'''

[[levels]]
title = "Level 32"
data = '''
 ######
 #@   ##
 ##$   #
### .  #
# $ #$##
# .  .#
####  #
   ####
'''

[[levels]]
title = "Level 33"
data = '''
#####
#   ###
#  $  #
##$$ .#
 #@ . #
 ## # #
  #  .#
  #####
'''

[[levels]]
title = "Level 34"
data = '''
#####
#   ####
# $$   #
# .#.  #
#  ## ##
#  ##$#
# @  .#
#######
'''

[[levels]]
title = "Level 35"
data = '''
######
# .  #
# .# ###
# @$$  #
# $.   #
########
'''

[[levels]]
title = "Level 36"
data = '''
########
# @.#  #
# .$ . #
#  #$  #
#  $  ##
###  ##
  #  #
  ####
'''

[[levels]]
title = "Level 37"
data = '''
 #######
##   . #
# $  $@#
#.$.####
#  ##
#  #
#  #
####
'''

[[levels]]
title = "Level 38"
data = '''
######
# .  #
#  #@#
#  $ ##
##$#  #
#   # #
#. *  #
#######
'''

[[levels]]
title = "Level 39"
data = '''
######
# .  #
#  #@#
#  $ ##
##$#  #
#   # #
#. *  #
#######
'''

[[levels]]
title = "Level 40"
data = '''
  ####
###  ###
# .. $.#
#  $$ @#
####   #
   #####
'''

[[levels]]
title = "Level 41"
data = '''
    ####
    #@ #
##### .#
# $ $ $#
#   .  #
### .  #
  ######
'''

[[levels]]
title = "Level 42"
data = '''
########
#   #  #
# #.$ $#
#   $  #
#####. #
  #   @#
  #   .#
  ######
'''

[[levels]]
title = "Level 43"
data = '''
   ####
  ##@ ##
 ##  ..#
## $#$##
#   $. #
#  #   #
#    ###
######
'''

[[levels]]
title = "Level 44"
data = '''
######
#   @#
# $$####
# $ .  #
## #.# #
#.   # #
#      #
########
'''

[[levels]]
title = "Level 45"
data = '''
   ####
   #  #
#### $##
# @$.  #
# ##   #
#   ## #
#   * .#
########
'''

[[levels]]
title = "Level 46"
data = '''
   #####
   # @ #
 ###   #
 # $ $##
## $  #
#.  # #
#..   #
#######
'''

[[levels]]
title = "Level 47"
data = '''
   #####
####. @#
#  .$  #
# #  ###
# $ $ .#
####   #
   #####
'''

[[levels]]
title = "Level 48"
data = '''
########
#  .# @#
# # $  #
# $.#$ #
## .   #
 #  ####
 ####
'''

[[levels]]
title = "Level 49"
data = '''
#######
#     #
#.## .#
#*  $@#
#  #$ #
#  #  #
#######
'''

[[levels]]
title = "Level 50"
data = '''
####
#. #
# $#
#  #####
# .$ @ #
# .$ # #
###    #
  ######
'''

[[levels]]
title = "Level 51"
data = '''
########
#      #
# #$   #
# $ @#.#
##$#.  #
 #    .#
 #######
'''

[[levels]]
title = "Level 52"
data = '''
######
#  . #
#    ###
# #$$. #
#.  ## #
#@$ ## #
###    #
  ######
'''
